language: bash
services: docker

env:
  global:
    image=eclecticiq/package
  matrix:
    - version=1.11.0 latest=true
    - version=1.10.2
    - version=1.10.1
    - version=1.10.0
script:
  - travis_retry docker build --build-arg VERSION=$version --tag "$image:$version" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag "$image:$latest" "$image:latest"
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $image;
    fi
