language: bash
services: docker

env:
  image=eclecticiq/package

script:
  - travis_retry docker build --tag "$image:latest" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $image;
    fi
