language: bash
services: docker

env:
  global:
    image=eclecticiq/package
  matrix:
    - version=1.11.0 latest=true
    - version=1.10.2
    - version=1.10.1
    - version=1.10.0

jobs:
  include:
    - stage: build
      script: travis_retry docker build --build-arg FPM_VERSION=$version --tag "$image:$version" .
    - stage: tag latest
      script: docker tag "$image:$version" "$image:latest"
      env: latest=true
    - stage: push
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push $image;
      branch: master
